// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwIdfbR4ycwoskcsdympicdZSZWhZkrc',
    appId: '1:1079251771324:web:6f1b1097efb4a2b63355b9',
    messagingSenderId: '1079251771324',
    projectId: 'trucley',
    authDomain: 'trucley.firebaseapp.com',
    databaseURL: 'https://trucley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trucley.firebasestorage.app',
    measurementId: 'G-4WJ8EMLGF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIppAZgcUoCbAt-Xi6oljWDUkYtY6Wd4',
    appId: '1:1079251771324:android:6a56ff38b5b263ba3355b9',
    messagingSenderId: '1079251771324',
    projectId: 'trucley',
    databaseURL: 'https://trucley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trucley.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Z-M9cSChVjMasVI9t5tloA3pJOhTja0',
    appId: '1:1079251771324:ios:608d8d7aaa3308cb3355b9',
    messagingSenderId: '1079251771324',
    projectId: 'trucley',
    databaseURL: 'https://trucley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trucley.firebasestorage.app',
    iosBundleId: 'com.example.trucley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Z-M9cSChVjMasVI9t5tloA3pJOhTja0',
    appId: '1:1079251771324:ios:608d8d7aaa3308cb3355b9',
    messagingSenderId: '1079251771324',
    projectId: 'trucley',
    databaseURL: 'https://trucley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trucley.firebasestorage.app',
    iosBundleId: 'com.example.trucley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMwIdfbR4ycwoskcsdympicdZSZWhZkrc',
    appId: '1:1079251771324:web:d715eb432691540b3355b9',
    messagingSenderId: '1079251771324',
    projectId: 'trucley',
    authDomain: 'trucley.firebaseapp.com',
    databaseURL: 'https://trucley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trucley.firebasestorage.app',
    measurementId: 'G-RWSEC09WMK',
  );
}
